Крестики-нолики
chezapacan/CSharpEducation pull request #1
Opened 2023-07-25 11:41 UTC by chezapacan

2023-07-25 12:05 UTC, Dezodemius requested changes

2023-07-25 12:05 UTC, Dezodemius commented on Task2/Program.cs
> +  static bool NewGame()
Надо подумать над названием метода. Пока оно не говорит, что делает. StartNewGame можно

2023-07-25 12:05 UTC, Dezodemius commented on Task2/TicTacToe.cs
> +  /// <summary>
Нужны регионы

2023-07-25 12:05 UTC, Dezodemius commented on Task2/TicTacToe.cs
> +    this.field = new string[3, 3] { { "1", "2", "3" }, { "4", "5", "6" }, { "7", "8", "9" } };
Давай создание в отдельном методе сделаем. Как вариант. Поле можно в конструкторе создавать

2023-07-25 12:05 UTC, Dezodemius commented on Task2/TicTacToe.cs
> +      mark = isXTurn ? "X" : "O";
строки нужно вынести в константы

2023-07-25 12:05 UTC, Dezodemius commented on Task2/TicTacToe.cs
> +    if (this.field[row, 0] == this.field[row, 1] && this.field[row, 1] == this.field[row, 2])
Давай объедим ифы в один большой. Либо пробежимся в цикле по комбинациям

2023-07-25 12:05 UTC, Dezodemius commented on Task3/ConsolePhoneBook.cs
> +
Убрать пустую строку

2023-07-25 12:05 UTC, Dezodemius commented on Task3/ConsolePhoneBook.cs
> +  public static void PrintPhoneBook(PhoneBook phoneBook)
А что если... засунуть это в ToString? Чтобы возвращало большую строку. А мы её уже как хотим отобразим?

2023-07-25 12:05 UTC, Dezodemius commented on Task3/ConsolePhoneBook.cs
> +  public static void PrintPhoneBook(PhoneBook phoneBook)
Аааааа... Это меню. Тогда не надо. Тогда нужно название соответствующее. И это не должно быть в этом классе

2023-07-25 12:05 UTC, Dezodemius commented on Task3/ConsolePhoneBook.cs
> +  private static int ChooseOption(int optionsCount)
Это тоже нужно вынести

2023-07-25 12:05 UTC, Dezodemius commented on Task3/ConsolePhoneBook.cs
> +    Environment.Exit(0);
Не стоит здесь делать завершение

2023-07-25 12:05 UTC, Dezodemius commented on Task3/ConsolePhoneBook.cs
> +    return (phoneBook) => phoneBook.Remove(phone);
А почему это так? Для чего через делегат Action?

2023-07-25 12:05 UTC, Dezodemius commented on Task3/ConsolePhoneBook.cs
> +    Environment.Exit(0);
Аааа, я тупой. Ладно, давай так всё оставим. Не будем ничего выносить.
ps к слову о важности понимания названий класса и что он будет делать

2023-07-25 12:05 UTC, Dezodemius commented on Task3/PhoneBook.cs
> +  public List<Abonent> Abonents { get => abonents; }
Поле не нужно, если свойство не добавляет логики. 
`Abonents { get; }`

2023-07-25 12:05 UTC, Dezodemius commented on Task3/PhoneBook.cs
> +  private PhoneBook()
Конструктор должен быть в конце класса. Всё по соглашению о кодировании. Там в разделе с регионами. Кстати, класс большой, нужны регионы

2023-07-25 12:05 UTC, Dezodemius commented on Task3/PhoneBook.cs
> +    var reader = new StreamReader("phonebook.txt");
Путь к файлу нужно вынести в отдельный класс

2023-07-25 12:05 UTC, Dezodemius commented on Task3/phonebook.txt
> +111:name1
Пусть этот файл не будет в репозитории. Он должен создаваться классом и им же удаляться (если нужно такое)

2023-07-25 12:49 UTC, chezapacan commented on Task2/TicTacToe.cs
> +  /// <summary>
Внутри регионов нужно пустой строкой отделять?
`#region Название региона

some code

#endregion`

2023-07-25 14:39 UTC, chezapacan commented on Task3/ConsolePhoneBook.cs
> +    return (phoneBook) => phoneBook.Remove(phone);
Функция GetOptions принимает словарь (options) с названиями опций (ключами string) и то, что они должны выполнять (значениями Action<PhoneBook>). 
```c#
    // В зависимости от выбора "Меню" (choosenOption = 0) или "Абонента" (choosenOption > 0) меняются допустимые опции.
    var options = chosenOption == 0
    ? new Dictionary<string, Action<PhoneBook>>()
    {
      {"Добавить нового абонента", AddAbonent},
      {"Поиск пользователя по телефону", GetAbonent},
      {"Поиск телефонных номеров по имени", GetPhoneNumber},
      {"Сохранение и выход", SaveAbonents},
    }
    : new Dictionary<string, Action<PhoneBook>>()
    {
      {"Удалить абонента из телефонной книги", RemoveAbonent(chosenAbonent.Phone)},
      {"Изменить имя абонента", ChangeAbonentName(chosenAbonent.Phone)},
      {"Изменить телефонный номер абонента", ChangeAbonentPhoneNumber(chosenAbonent.Phone)},
    };

    GetOptions(options, phoneBook);
``` 
Т.к. для работы с абонентом требуется передача в аргумент его номера, в функции абонента я передаю номер (phone) и возвращаю новую функцию. В получившимся словаре для абонента функции вызываются, возвращая подходящую Action< PhoneBook>.
```c#
  private static Action<PhoneBook> RemoveAbonent(string phone)
  {
    return (phoneBook) => phoneBook.Remove(phone);
  }
```

2023-07-25 16:22 UTC, chezapacan commented on Task2/Program.cs
> +  static bool NewGame()
Переименовал в NewGameStarted

2023-07-25 16:23 UTC, chezapacan commented on Task2/TicTacToe.cs
> +  /// <summary>
Добавил регионы

2023-07-25 16:25 UTC, chezapacan commented on Task2/TicTacToe.cs
> +    this.field = new string[3, 3] { { "1", "2", "3" }, { "4", "5", "6" }, { "7", "8", "9" } };
Сделал создание пустого поля в новом методе CreateEmptyField

2023-07-25 16:25 UTC, chezapacan commented on Task2/TicTacToe.cs
> +      mark = isXTurn ? "X" : "O";
Вынес в константы

2023-07-25 16:26 UTC, chezapacan commented on Task2/TicTacToe.cs
> +    if (this.field[row, 0] == this.field[row, 1] && this.field[row, 1] == this.field[row, 2])
Объединил в один большой

2023-07-25 16:26 UTC, chezapacan commented on Task3/ConsolePhoneBook.cs
> +
Убрал

2023-07-25 16:26 UTC, chezapacan commented on Task3/ConsolePhoneBook.cs
> +  public static void PrintPhoneBook(PhoneBook phoneBook)
Переименовал в PrintPhoneBookMenu

2023-07-25 16:27 UTC, chezapacan commented on Task3/ConsolePhoneBook.cs
> +    Environment.Exit(0);
Поменял название класса для работы в консоли на PhoneBookConsoleWorker

2023-07-25 16:28 UTC, chezapacan commented on Task3/PhoneBook.cs
> +  public List<Abonent> Abonents { get => abonents; }
Убрал поле

2023-07-25 16:29 UTC, chezapacan commented on Task3/PhoneBook.cs
> +  private PhoneBook()
Добавил регионы перенес конструктор

2023-07-25 16:30 UTC, chezapacan commented on Task3/PhoneBook.cs
> +    var reader = new StreamReader("phonebook.txt");
Вынес в отдельный класс в том же файле

2023-07-25 17:33 UTC, chezapacan commented on Task3/phonebook.txt
> +111:name1
Вынес прочтение из файла в отдельный метод. Файл создается сам в папке с исполняемым файлом.

2023-07-26 09:39 UTC, Dezodemius approved these changes

2023-07-26 09:39 UTC, merged