Task4 (Repository)
chezapacan/CSharpEducation pull request #2
Opened 2023-08-06 07:32 UTC by chezapacan

2023-08-19 09:40 UTC, Dezodemius requested changes

2023-08-19 09:40 UTC, Dezodemius commented on Task4/Entities/FileEntity.cs
> +  /// Инийиализация сущности.
опечатка

2023-08-19 09:40 UTC, Dezodemius commented on Task4/Repositories/MemoryRepository.cs
> +public class MemoryRepository<T> : IRepository<T> where T : IEntity
Давай создадим ещё и MemoryEntity для этого репозитория

2023-08-19 10:38 UTC, chezapacan commented on Task4/Entities/FileEntity.cs
> +  /// Инийиализация сущности.
Исправил

2023-08-19 10:39 UTC, chezapacan commented on Task4/Repositories/MemoryRepository.cs
> +public class MemoryRepository<T> : IRepository<T> where T : IEntity
Создал

2023-08-28 05:49 UTC, Dezodemius approved these changes

2023-08-28 05:49 UTC, Dezodemius commented on Task4/Entities/FileEntity.cs
> +  /// Инициализация сущности.
```
/// <summary>
/// Конструктор.
/// </summary>
```

2023-08-29 15:22 UTC, chezapacan commented on Task4/Entities/FileEntity.cs
> +  /// Инициализация сущности.
Конструктор.

2023-08-29 20:43 UTC, Dezodemius approved these changes

2023-09-06 16:01 UTC, merged